name: HTML Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Super-Linter
      uses: github/super-linter@v7
      env:
        VALIDATE_HTML: true
        FILES: templates/**/*.html.tmpl
        OUTPUT_FORMAT: sarif
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set GitHub token
    - name: Archive Lint Results
      uses: actions/upload-artifact@v4
      with:
        name: html-lint-results
        path: super-linter.sarif
