name: HTML Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Super-Linter
      uses: github/super-linter@v7
      with:
        run-linter: html
        linter-config: .github/linter.yml
        lint-staged: false
        disable-cache: true
        fail-on-warning: false
        fail-on-error: true
        enable-all-linters: false
        linters-to-run: html
        default_branch: master # Ensure the correct branch is set
      env:
        VALIDATE_HTML: true
        FILES: templates/**/*.html.tmpl
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set GitHub token
        GITHUB_WORKSPACE: /home/runner/work/ods-document-generation-templates/ods-document-generation-templates # Explicitly set the workspace path
    - name: Archive Lint Results
      uses: actions/upload-artifact@v4
      with:
        name: html-lint-results
        path: super-linter.sarif
